name: Sugest達o
description: Adicionar uma sugest達o para o mod.
labels: ["sugest達o"]
assignees: leogianfagna
body:
  - type: textarea
    attributes:
      label: Sugest達o
      description: Descreva a sua ideia para ser implementada.
    validations:
      required: true
